"""Add IPv6 column

Revision ID: 528cb85d6ad3
Revises:
Create Date: 2021-07-30 19:05:31.695486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '528cb85d6ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazonservers', sa.Column('ipv6', postgresql.INET(), nullable=True))
    op.add_column('googleservers', sa.Column('ipv6', postgresql.INET(), nullable=True))
    op.add_column('microsoftservers', sa.Column('ipv6', postgresql.INET(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microsoftservers', 'ipv6')
    op.drop_column('googleservers', 'ipv6')
    op.drop_column('amazonservers', 'ipv6')
    # ### end Alembic commands ###
