"""add cspname column to amazonimages

Revision ID: 79a9f370cd0d
Revises: ee82c541fae0
Create Date: 2022-03-01 00:03:58.091896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a9f370cd0d'
down_revision = 'ee82c541fae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazonimages', sa.Column('cspname', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazonimages', 'cspname')
    # ### end Alembic commands ###
