"""Add Servers ID

Revision ID: b381843009e0
Revises: 528cb85d6ad3
Create Date: 2021-07-30 00:15:20.918363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

# revision identifiers, used by Alembic.
revision = 'b381843009e0'
down_revision = '528cb85d6ad3'
branch_labels = None
depends_on = None

tablenames = ['amazonservers', 'googleservers', 'microsoftservers']

def upgrade():
    # manual commands
    for tablename in tablenames:
        op.drop_constraint('%s_pkey' % (tablename), tablename, type_='primary')
        op.execute(CreateSequence(Sequence('%s_id_seq' % (tablename))))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazonservers', sa.Column(
        'id', sa.Integer(), nullable=False, server_default=sa.text("nextval('amazonservers_id_seq'::regclass)"))
    )
    op.alter_column('amazonservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=True)
    op.add_column(
        'googleservers', sa.Column('id', sa.Integer(), nullable=False, server_default=sa.text("nextval('googleservers_id_seq'::regclass)"))
    )
    op.alter_column('googleservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=True)
    op.add_column('microsoftservers', sa.Column(
        'id', sa.Integer(), nullable=False, server_default=sa.text("nextval('microsoftservers_id_seq'::regclass)"))
    )
    op.alter_column('microsoftservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=True)
    # ### end Alembic commands ###
    # manual commands
    for tablename in tablenames:
        op.create_primary_key('%s_pkey' % (tablename), tablename, ['id'])


def downgrade():
    # manual commands
    for tablename in tablenames:
        op.drop_constraint('%s_pkey' % (tablename), tablename, type_='primary')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('microsoftservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=False)
    op.drop_column('microsoftservers', 'id')
    op.alter_column('googleservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=False)
    op.drop_column('googleservers', 'id')
    op.alter_column('amazonservers', 'ip',
               existing_type=postgresql.INET(),
               nullable=False)
    op.drop_column('amazonservers', 'id')
    # ### end Alembic commands ###
    # manual commands
    for tablename in tablenames:
        op.create_primary_key('%s_pkey' % (tablename), tablename, ['ip', 'region'])
        op.execute('drop sequence %s_id_seq' % (tablename))
